# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Cybilltek' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cybilltek
  pod 'Kingfisher', '~> 7.0'

end
